name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix: 
        sdk-minor-version: [ 401, 402, 403, 404, 405, 406, 407, 408, 409 ]
        
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.${{ matrix.sdk-minor-version }}'
      
    - name: Build + Publish
      run: dotnet publish -c Release
      
    - name: Test single file binary runs with normal permissions ok
      run: bin/Release/netcoreapp3.1/linux-x64/publish/BundlingIssue
      
    - name: Test single file binary runs with root ok
      run: sudo bin/Release/netcoreapp3.1/linux-x64/publish/BundlingIssue
      
    - name: Add Systemd Unit File
      run: | 
        cat <<-EOF | sudo tee /etc/systemd/system/bundlingissue.service >/dev/null
        [Unit]
        Description=BundlingIssue
        After=network.target

        [Service]
        ExecStart=$PWD/bin/Release/netcoreapp3.1/linux-x64/publish/BundlingIssue

        [Install]
        WantedBy=multi-user.target

        EOF

    - name: Start Systemd Service
      run: |
        sudo systemctl enable bundlingissue.service
        sudo systemctl start bundlingissue.service

    - name: Print Syslog (for reference)
      run: |
        tail -n 20 /var/log/syslog

    - name: Check if a fatal error occurred in syslog
      run: |
        cat /var/log/syslog | not grep "A fatal error was encountered. Could not extract contents of the bundle"
